-- Tool-level context mapping, output contracts, guardrails, and prompt versioning.
alter table public.prompts add column if not exists context_fields jsonb not null default '[]'::jsonb;
alter table public.prompts add column if not exists task_template text;
alter table public.prompts add column if not exists required_output text;
alter table public.prompts add column if not exists guardrails text;
alter table public.prompts add column if not exists prompt_version text not null default '1.0';

comment on column public.prompts.context_fields is 'Business Profile fields approved for this tool. Member clients receive this only after tier authorization.';
comment on column public.prompts.prompt_version is 'Version captured with each prompt copy or generation in input_payload.prompt_version.';

-- Safe defaults cover administrator-created tools; the official catalog is specialized below.
update public.prompts set
  context_fields = case
    when context_fields = '[]'::jsonb then '["business_name","industry","business_stage","business_description","services","target_market","ideal_customer","business_goals","primary_business_challenges"]'::jsonb
    else context_fields end,
  task_template = coalesce(nullif(task_template,''), user_prompt_template),
  required_output = coalesce(nullif(required_output,''), nullif(output_format,''), E'1. Summary\n2. Prioritized Recommendations\n3. Next Actions\n4. Assumptions and Missing Information\n5. Measures'),
  guardrails = coalesce(nullif(guardrails,''), 'Clearly distinguish recommendations, targets, assumptions, and verified results. Do not invent facts, evidence, financial projections, completed actions, or achieved outcomes.'),
  prompt_version = case when prompt_version = '1.0' then '1.1' else prompt_version end;

with config(slug,context_fields,task_template,required_output,specific_guardrail) as (values
('business-profile-enhancer','["business_name","industry","business_stage","years_in_business","business_description","products","services","target_market","ideal_customer","business_goals"]'::jsonb,
 'Strengthen the reviewed business profile for the intended audience using the proof points in the tool-specific inputs. Preserve accurate claims and make the positioning clear and credible.',
 '1. Positioning Assessment\n2. Recommended Profile (120 words)\n3. Short Profile (40 words)\n4. Key Proof Points\n5. Missing Information to Confirm',
 'Do not add credentials, customers, results, or differentiators that were not provided.'),
('elevator-pitch-creator','["business_name","industry","business_description","services","target_market","ideal_customer","business_goals"]'::jsonb,
 'Create concise elevator pitches that explain who the business serves, the value offered, and a credible reason to continue the conversation.',
 '1. Core Value Message\n2. 15-Second Pitch\n3. 30-Second Pitch\n4. Conversational Networking Pitch\n5. Delivery Notes\n6. Recommended Follow-Up Question',
 'Do not promise customer results or use unsupported superlatives.'),
('tagline-generator','["business_name","industry","business_description","products","services","ideal_customer","business_goals"]'::jsonb,
 'Develop distinctive tagline directions aligned with the reviewed positioning, customer promise, and requested tone.',
 '1. Positioning Theme\n2. Direct Taglines (5)\n3. Aspirational Taglines (5)\n4. Memorable Taglines (5)\n5. Strongest 3 With Rationale\n6. Usage Guidance',
 'Do not imply guarantees or market leadership without evidence.'),
('social-media-post','["business_name","industry","business_description","products","services","ideal_customer","business_goals"]'::jsonb,
 'Write a platform-appropriate social media post that communicates the supplied topic to the intended audience and supports the requested action.',
 '1. Recommended Angle\n2. Opening Hook\n3. Final Post Copy\n4. Call to Action\n5. Five Relevant Hashtags\n6. Optional Visual Direction',
 'Do not claim engagement, reach, customer results, or completed activity without evidence.'),
('customer-faq-builder','["business_name","industry","business_description","products","services","target_market","ideal_customer"]'::jsonb,
 'Build a clear customer FAQ that answers the supplied questions, respects stated policies, and identifies important gaps.',
 '1. FAQ Introduction\n2. Customer Questions and Answers\n3. Objection-Handling Questions\n4. Three Missing Questions to Add\n5. Policy or Information Gaps\n6. Recommended Placement',
 'Do not invent policies, prices, guarantees, availability, or service terms.'),
('ideal-customer-profile','["business_name","industry","business_stage","business_description","products","services","target_market","ideal_customer","business_goals","geographic_market"]'::jsonb,
 'Create an evidence-aware ideal customer profile that helps the business focus positioning, outreach, and qualification.',
 '1. Primary Customer Segment\n2. Demographics / Firmographics\n3. Needs\n4. Pain Points\n5. Buying Triggers\n6. Purchase Objections\n7. Decision Criteria\n8. Messaging Recommendations\n9. Validation Questions',
 'Label inferred characteristics as hypotheses to validate rather than established customer facts.'),
('basic-swot-analysis','["business_name","industry","business_stage","years_in_business","business_description","products","services","target_market","business_goals","geographic_market","primary_business_challenges","assessment_priorities"]'::jsonb,
 'Conduct a practical SWOT analysis tied to the reviewed goal and market information, then translate the analysis into focused action.',
 '1. Strengths\n2. Weaknesses\n3. Opportunities\n4. Threats\n5. Strategic Implications\n6. Top 3 90-Day Actions\n7. Assumptions and Evidence Needed',
 'Separate internal factors from external factors and do not present unverified market claims as facts.'),
('professional-business-bio','["business_name","industry","business_description","services","years_in_business","target_market","business_certifications"]'::jsonb,
 'Write polished professional bios for the requested channels using only the supplied role, experience, credentials, and achievements.',
 '1. Positioning Summary\n2. 100-Word Professional Bio\n3. 50-Word Short Bio\n4. LinkedIn About Version\n5. Speaker Introduction\n6. Facts to Verify',
 'Do not create awards, credentials, experience, clients, or achievements.'),
('customer-value-proposition','["business_name","industry","business_description","products","services","target_market","ideal_customer","business_goals","primary_business_challenges"]'::jsonb,
 'Develop a differentiated customer value proposition grounded in the customer problem, the offer, and the evidence provided.',
 '1. Target Customer\n2. Customer Problem\n3. Core Value Proposition Statement\n4. Differentiated Benefits\n5. Proof Points\n6. Three Message Variations\n7. Claims Requiring Validation',
 'Do not invent quantified benefits, proof, or competitive superiority.'),
('keyword-generator','["business_name","industry","business_description","products","services","target_market","ideal_customer","geographic_market","primary_markets_served"]'::jsonb,
 'Create a focused keyword framework aligned with the business, geography, customer intent, and services provided.',
 '1. Search Intent Summary\n2. Awareness Keywords\n3. Consideration Keywords\n4. Purchase-Intent Keywords\n5. Local / Geographic Keywords\n6. Five Content Topics\n7. Validation and Research Notes',
 'Treat search demand and competition as unverified until confirmed with keyword data.'),
('seven-day-content-calendar','["business_name","industry","business_description","products","services","ideal_customer","business_goals"]'::jsonb,
 'Create a practical seven-day content calendar for the selected channel and objective using the reviewed audience and offer context.',
 'For each of Days 1-7 provide:\n- Day\n- Channel\n- Topic\n- Hook\n- Post Copy\n- CTA\n- Content Objective\nThen provide a weekly theme and reuse notes.',
 'Do not claim content was published or produced, and do not invent customer evidence.'),
('promotional-email','["business_name","industry","business_description","products","services","ideal_customer","business_goals"]'::jsonb,
 'Write a persuasive promotional email aligned with the offer, audience, and genuine timing supplied.',
 '1. Campaign Objective\n2. Five Subject Lines\n3. Preview Text\n4. Email Body\n5. Primary CTA\n6. Follow-Up Email\n7. Claims and Details to Verify',
 'Do not fabricate scarcity, deadlines, discounts, testimonials, or offer terms.'),
('linkedin-thought-leadership-post','["business_name","industry","business_description","services","ideal_customer","business_goals"]'::jsonb,
 'Turn the supplied insight and evidence into a credible LinkedIn thought-leadership post for the intended audience.',
 '1. Core Point of View\n2. Three Hook Options\n3. Final LinkedIn Post\n4. Practical Takeaway\n5. Conversation-Starting Close\n6. Evidence or Claims to Verify',
 'Do not manufacture personal experience, research, results, or third-party evidence.'),
('sales-outreach-message','["business_name","industry","business_description","products","services","ideal_customer","business_goals","primary_business_challenges"]'::jsonb,
 'Create relevant first-touch outreach that connects the prospect priority to a credible business value and a low-friction next step.',
 '1. Prospect Relevance Summary\n2. Email Subject Lines (3)\n3. Concise Email Version\n4. LinkedIn Connection Note\n5. LinkedIn Follow-Up\n6. Low-Friction CTA\n7. Personalization Checklist',
 'Do not claim knowledge about the prospect or proof that was not provided.'),
('referral-strategy-builder','["business_name","industry","business_description","services","ideal_customer","business_goals","geographic_market","primary_business_challenges"]'::jsonb,
 'Build a repeatable referral strategy around the ideal referral, likely partner types, and a genuine two-way value exchange.',
 '1. Referral Objective\n2. Ideal Referral Definition\n3. Referral Partner Types\n4. Mutual Value Exchange\n5. Referral Ask Scripts\n6. Follow-Up Cadence\n7. Tracking Measures\n8. First 30 Days',
 'Do not assume partners have agreed to participate or promise referral volume.'),
('customer-retention-plan','["business_name","industry","business_stage","business_description","products","services","ideal_customer","business_goals","primary_business_challenges"]'::jsonb,
 'Create a supportable customer retention plan based on stated customer risks and available capacity.',
 '1. Retention Objective\n2. Customer Risk Segments\n3. Onboarding Improvements\n4. Communication Cadence\n5. Loyalty and Value Actions\n6. Recovery Steps\n7. Five KPIs\n8. 30-Day Implementation Plan',
 'Do not assert churn causes or retention improvements without data.'),
('90-day-growth-plan','["business_name","industry","business_stage","years_in_business","business_description","services","target_market","ideal_customer","business_goals","geographic_market","primary_markets_served","markets_to_enter","primary_business_challenges","assessment_priorities"]'::jsonb,
 'Create a realistic 90-day growth plan for {{business_name}} focused on {{goal}}. Account for the execution capacity described above. Prioritize high-impact activities without creating an unrealistic workload. Evaluate how the tool goal supports the broader business goals; when that relationship cannot be determined, identify the additional metrics needed.',
 '1. Executive Summary\n\n2. 90-Day Objective\n   - Primary goal\n   - Key assumptions\n   - Definition of success\n\n3. Month 1: Foundation and Pipeline Building\n   - Milestones\n   - Weekly actions\n   - Owner\n   - KPIs\n\n4. Month 2: Outreach and Conversion\n   - Milestones\n   - Weekly actions\n   - Owner\n   - KPIs\n\n5. Month 3: Conversion and Optimization\n   - Milestones\n   - Weekly actions\n   - Owner\n   - KPIs\n\n6. Weekly Activity Targets\n   - qualified prospects identified\n   - outreach attempts\n   - referral conversations\n   - discovery calls\n   - proposals\n   - new clients\n\n7. Top 3 Priorities\n\n8. Risks and Constraints\n\n9. Next 7 Days\n   - five specific actions\n\n10. Measurement Plan\n   - activity metrics\n   - pipeline metrics\n   - outcome metrics\n\nUse concise, practical business language.',
 'Do not guarantee client acquisition, revenue growth, or any other outcome. Identify capacity conflicts and distinguish targets from achieved results.'),
('event-promotion-kit','["business_name","industry","business_description","services","ideal_customer","business_goals","geographic_market"]'::jsonb,
 'Build a coordinated event promotion kit around the supplied event value, audience, channels, and actual timeline.',
 '1. Event Positioning\n2. Audience and Value Proposition\n3. Landing Page Copy\n4. Three Promotional Emails\n5. Five Social Posts\n6. Partner Promotion Copy\n7. Promotion Timeline\n8. Registration KPIs',
 'Do not invent speakers, dates, prices, sponsors, capacity, or registration results.'),
('corporate-partnership-pitch','["business_name","industry","business_stage","business_description","products","services","target_market","business_goals","geographic_market","primary_business_challenges","business_certifications"]'::jsonb,
 'Develop a corporate partnership strategy that frames a credible mutual value exchange and a practical path to outreach.',
 '1. Partnership Objective\n2. Ideal Partner Types\n3. Value Exchange\n4. Target Partner Criteria\n5. Outreach Strategy\n6. Partnership Pitch\n7. Activation Concept\n8. 30-Day Action Plan\n9. Measures and Assumptions',
 'Do not imply partner interest, approval, commitments, or measurable value without evidence.'),
('sponsorship-outreach','["business_name","industry","business_description","services","target_market","ideal_customer","geographic_market"]'::jsonb,
 'Create a benefits-led sponsorship outreach package matched to the opportunity, prospective sponsor, and stated ask.',
 '1. Sponsorship Objective\n2. Sponsor Fit\n3. Value Proposition\n4. Outreach Email\n5. Three Sponsorship Levels\n6. Benefits by Level\n7. Follow-Up Sequence\n8. Fulfillment Questions',
 'Do not invent audience size, sponsor benefits, pricing, or commitments.'),
('capability-statement-outline','["business_name","industry","business_description","services","years_in_business","geographic_market","business_certifications","target_market"]'::jsonb,
 'Build an accurate, buyer-ready capability statement using the supplied competencies, differentiators, experience, and procurement information.',
 '1. Company Overview\n2. Core Competencies\n3. Differentiators\n4. Relevant Experience\n5. Certifications\n6. NAICS / Procurement Information if Provided\n7. Contact Section\n8. Recommended One-Page Layout\n9. Missing Information Flags',
 'Do not invent NAICS codes, certifications, registrations, contract history, clients, or performance results.'),
('vendor-readiness-assessment','["business_name","industry","business_stage","years_in_business","business_description","services","target_market","geographic_market","business_certifications","primary_business_challenges"]'::jsonb,
 'Assess vendor readiness against the target buyer requirements and the evidence actually supplied.',
 '1. Readiness Summary\n2. Readiness by Area\n3. Critical Gaps\n4. Credential and Evidence Checklist\n5. Delivery Capacity Risks\n6. 60-Day Action Plan\n7. Go / Prepare / Defer Recommendation',
 'Do not assign a definitive readiness score without stated criteria; explain the basis for any indicative rating.'),
('rfp-response-outline','["business_name","industry","business_description","services","business_certifications","geographic_market"]'::jsonb,
 'Organize a compliant, persuasive RFP response outline from the solicitation requirements, proposed solution, and available proof.',
 '1. Compliance Matrix\n2. Executive Summary Structure\n3. Technical Response Sections\n4. Management and Staffing Sections\n5. Past Performance Evidence Needs\n6. Pricing Inputs Needed\n7. Risks and Clarifications\n8. Review Checklist\n9. Submission Workplan',
 'Do not claim compliance, experience, staffing, certifications, or pricing that has not been verified.'),
('executive-business-summary','["business_name","industry","business_stage","years_in_business","business_description","services","business_goals","primary_business_challenges","assessment_priorities"]'::jsonb,
 'Create a concise executive business summary that separates current position, verified performance, priorities, risks, and decisions.',
 '1. Executive Summary\n2. Current Position\n3. Verified Performance Highlights\n4. Key Risks\n5. Top 3 Priorities\n6. Recommended Decision\n7. Next Actions\n8. Missing Information',
 'Do not create performance results or imply decisions were approved.'),
('executive-growth-brief','["business_name","industry","business_stage","business_description","services","business_goals","primary_business_challenges","assessment_priorities"]'::jsonb,
 'Prepare an evidence-aware executive growth brief that connects current position and pipeline information to decisions and next moves.',
 '1. Executive Summary\n2. Current Position\n3. Strategic Priorities\n4. Key Risks\n5. Growth Opportunities\n6. Recommended Actions\n7. KPIs\n8. Next Decision Points\n9. Assumptions and Data Gaps',
 'Do not present pipeline as revenue, forecast unsupported results, or imply recommendations were executed.'),
('12-month-strategic-plan','["business_name","industry","business_stage","years_in_business","business_description","products","services","target_market","business_goals","geographic_market","primary_business_challenges","assessment_priorities"]'::jsonb,
 'Translate the stated 12-month direction, baseline, and constraints into a sequenced strategic plan with clear decision points.',
 '1. Executive Direction\n2. 12-Month Outcomes\n3. Strategic Pillars\n4. Quarter 1 Objectives and Initiatives\n5. Quarter 2 Objectives and Initiatives\n6. Quarter 3 Objectives and Initiatives\n7. Quarter 4 Objectives and Initiatives\n8. Owners and Dependencies\n9. KPIs and Review Cadence\n10. Risks and Assumptions',
 'Do not treat targets as forecasts or assume resources and dependencies are secured.'),
('board-leadership-update','["business_name","industry","business_stage","business_goals","primary_business_challenges","assessment_priorities"]'::jsonb,
 'Create a leadership-ready update that distinguishes verified results, insights, risks, requests, and next-period priorities.',
 '1. Executive Summary\n2. Period Objectives\n3. Scorecard of Provided Results\n4. Wins and Misses\n5. Key Insights\n6. Risks and Mitigations\n7. Decisions / Support Required\n8. Next-Period Priorities\n9. Appendix Data Needs',
 'Do not manufacture results, trends, explanations, or leadership decisions.'),
('market-expansion-strategy','["business_name","industry","business_stage","business_description","products","services","target_market","business_goals","geographic_market","primary_markets_served","markets_to_enter","primary_business_challenges"]'::jsonb,
 'Evaluate the proposed market expansion using the supplied offer, evidence, assets, and constraints, then define decision gates.',
 '1. Expansion Objective\n2. Target Market Definition\n3. Market Attractiveness Hypotheses\n4. Priority Segments\n5. Entry Options\n6. Recommended Entry Approach\n7. Partnerships and Assets\n8. 12-Month Roadmap\n9. Risks and Assumptions\n10. Decision Gates and Research Needed',
 'Do not invent market size, demand, competitor facts, costs, or entry outcomes.'),
('economic-impact-narrative','["business_name","industry","years_in_business","business_description","products","services","target_market","geographic_market","primary_markets_served","business_goals"]'::jsonb,
 'Write an evidence-based economic impact narrative for the intended audience using only the supplied reach and impact data.',
 '1. Executive Summary\n2. Business and Community Context\n3. Direct Economic Effects\n4. Indirect / Supply-Chain Effects\n5. Community Effects\n6. Geographic Reach\n7. Evidence Table\n8. Missing Data and Collection Plan\n9. Short Stakeholder Narrative',
 'Do not create jobs, spending, revenue, demographic impact, multipliers, or community outcomes.'),
('supplier-diversity-outreach','["business_name","industry","business_description","services","target_market","geographic_market","business_certifications"]'::jsonb,
 'Create credible supplier diversity outreach aligned with the target program, relevant capabilities, certifications, and available proof.',
 '1. Buyer / Program Fit\n2. Capability Positioning\n3. Certification Relevance\n4. Outreach Email\n5. Follow-Up Cadence\n6. Conversation Talking Points\n7. Readiness Checklist\n8. Missing Proof',
 'Do not claim certification, program eligibility, buyer interest, or past performance without evidence.'),
('executive-presentation','["business_name","industry","business_stage","business_description","business_goals","primary_business_challenges","assessment_priorities"]'::jsonb,
 'Shape a decision-focused executive presentation for the supplied audience, objective, and verified evidence.',
 '1. Presentation Objective\n2. Audience Considerations\n3. Slide-by-Slide Outline\n4. Key Message for Each Slide\n5. Recommended Visual for Each Slide\n6. Decision Points\n7. Speaker Notes\n8. Evidence Gaps and Appendix',
 'Do not create evidence, decisions, results, or executive endorsement.'),
('investment-readiness-plan','["business_name","industry","business_stage","years_in_business","business_description","products","services","target_market","business_goals","primary_business_challenges"]'::jsonb,
 'Assess investment readiness from the capital need, financial information, traction, team evidence, and supporting documents supplied.',
 '1. Readiness Summary\n2. Capital Need and Use of Funds\n3. Financial Readiness\n4. Traction and Market Evidence\n5. Team Readiness\n6. Document Checklist\n7. Narrative Priorities\n8. Risks and Gaps\n9. 90-Day Readiness Plan\n10. Questions for Advisors',
 'Do not invent valuation, projections, financial performance, investor interest, or funding probability.'),
('growth-roadmap','["business_name","industry","business_stage","years_in_business","business_description","products","services","target_market","business_goals","geographic_market","primary_business_challenges","assessment_priorities"]'::jsonb,
 'Create a sequenced growth roadmap from the current baseline to the stated destination while respecting resources, constraints, and priorities.',
 '1. Destination and Definition of Success\n2. Current Baseline\n3. Strategic Priorities\n4. Phase 1: Foundation\n5. Phase 2: Build\n6. Phase 3: Scale\n7. Milestones and Dependencies\n8. Measures\n9. Decision Gates\n10. Risks and Alternatives\n11. Next Five Actions',
 'Do not assume resources, milestones, or growth outcomes are secured.' )
)
update public.prompts p set
  context_fields = c.context_fields,
  task_template = c.task_template,
  required_output = replace(c.required_output, '\n', E'\n'),
  guardrails = 'Clearly distinguish recommended actions, targets, assumptions, and achieved results. Do not claim an action was taken or an outcome achieved unless the member explicitly provides evidence. ' || c.specific_guardrail,
  prompt_version = '1.1',
  updated_at = now()
from config c where p.slug = c.slug;

-- Historical strategies and activity keep their original input_payload. New activity
-- captures business_context_snapshot, guided_responses, and prompt_version in that JSON.
